[package]
name = "libwinpalisade"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.59.0", features=["Win32_System","Win32_Security","Win32_System_SystemInformation"] }
windows-registry = "0.4.0"

# Logging
log = "0.4"
pretty_env_logger = "0.4"